apiVersion: v1
data:
  DB_NAME: dev
  DOCKER_HOST: 10.0.0.113
kind: ConfigMap
metadata:
  labels:
    env: dev
  name: frontend-config-dm28hf8hf7
  namespace: dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    env: dev
  name: dt-twinarcpro-frontend
  namespace: dev
spec:
  ports:
  - nodePort: 30035
    port: 30035
    targetPort: 30035
  selector:
    app: dt-twinarcpro-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dt-twinarcpro-frontend
    env: dev
  name: dt-twinarcpro-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dt-twinarcpro-frontend
  template:
    metadata:
      labels:
        app: dt-twinarcpro-frontend
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - pnpm turbo run dev
        envFrom:
        - configMapRef:
            name: frontend-config-dm28hf8hf7
        image: privaterepo.com:5000/twinarc-dev:dt-twinarcpro-frontend-dev-126
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 30035
        name: frontend
        ports:
        - containerPort: 30035
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 30035
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: true
          runAsGroup: 0
          runAsUser: 0
      hostAliases:
      - hostnames:
        - dev.twinarcpro.eminds.ai
        - api.dev.twinarcpro.eminds.ai
        - gateway.dev.twinarcpro.eminds.ai
        - cap.dev.twinarcpro.eminds.ai
        ip: 10.0.0.99
      nodeSelector:
        node-type: twinarcworker2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    env: dev
  name: dt-twinarcpro-frontend
  namespace: dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dt-twinarcpro-frontend
