apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-twinarcpro-frontend
  labels:
    app: dt-twinarcpro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dt-twinarcpro-frontend
  template:
    metadata:
      labels:
        app: dt-twinarcpro-frontend
    spec:
      containers:
        - name: frontend
          image: dt-twinarcpro-frontend
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 30035
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
